-- =====================================================
-- Customer Data Import SQL
-- Generated from customer list (407 customers)
-- Format: Customer | Cust_ID
-- Note: Customers without Cust_ID will have CODE as NULL
-- =====================================================

-- Customers with Cust_ID
INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'AA_NJ', '1000025774', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025774');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_CQ', '1000911465', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911465');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_CS', '1000911464', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911464');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_QC', '1000158672', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000158672');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_GZ', '1000911462', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911462');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_LF', '1000019992', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019992');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_NC', '1000157796', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000157796');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_Sum', '1000001833', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000001833');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ADIENT_TZ', '1000173302', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000173302');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_ZQ', '1000166712', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166712');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Adient_HF', '1000170110', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000170110');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'AISH_FS', '1000033000', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033000');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Aiways_SR', '1000037397', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000037397');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Automobile_NJ', '1000010729', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010729');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'AKA Otomotiv', '1000004541', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000004541');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'AYM', '1000032870', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032870');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BAIC_BJ', '1000013483', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000013483');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BAIC_GZ', '1000018935', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018935');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BAIC_Powertrain', '1000911527', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911527');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Baoneng_SZ', '1000012826', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012826');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BBAC_BJ', '1000010900', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010900');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BHSS_NJ', '1000025204', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025204');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BHSS_SH', '1000021132', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021132');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BHSS_WH', '1000024060', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024060');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BHSS_YT', '1000026075', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026075');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Bonaire_WH', '1000911461', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911461');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Borgward_BJ', '1000032610', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032610');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_BJ', '1000911447', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911447');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_CC', '1000902866', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000902866');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_CQ', '1000015383', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015383');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_GZ', '1000026502', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026502');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_SH', '1000009914', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000009914');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_TC', '1000031578', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000031578');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_WH', '1000014566', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014566');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_CS', '1000013111', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000013111');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_HF', '1000173685', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000173685');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_ZZ', '1000173211', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000173211');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_SW', '1000167764', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000167764');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_SZ', '1000007685', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007685');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BYD_XA', '1000007660', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007660');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Buep', '1000000644', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000000644');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_BJ', '1000012241', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012241');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_CQ', '1000007657', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007657');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_DZ', '1000911538', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911538');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_HF', '1000019881', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019881');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_LY', '1000035562', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035562');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_NC', '1000167935', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000167935');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_AVATR', '1000166827', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166827');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CA_New_Energy_CQ', '1000045118', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000045118');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CAF_CQ', '1000012329', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012329');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CAF_HEB', '1000028384', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028384');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CAF_HZ', '1000040251', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040251');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Changyuan_CS', '1000029725', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029725');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chaoli_CQ', '1000020320', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020320');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_CV_WH', '1000033449', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033449');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_Eerduosi', '1000016026', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000016026');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_DL', '1000015772', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015772');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_FZ', '1000010721', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010721');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_KF', '1000035101', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035101');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_ZZ', '1000180339', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000180339');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_New_Energy_HF', '1000033224', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033224');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Chery_WH', '1000007649', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007649');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lixiang_BJ', '1000034268', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000034268');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lixiang_CZ', '1000152323', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000152323');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CIE_CC', '1000010912', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010912');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CIE_CD', '1000911521', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911521');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CIE_ND', '1000046450', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000046450');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CIE_TJ', '1000035523', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035523');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CIE_WGQ_SH', '1000911511', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911511');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CJLR_CSU', '1000020361', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020361');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CJLR_SH', '1000028777', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028777');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Cool_Wind_SH', '1000015923', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015923');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Cowin_WH', '1000028538', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028538');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CRH_SY', '1000024923', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024923');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DDHL_YC', '1000911500', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911500');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Denso_CQ', '1000035102', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035102');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Denso_CS', '1000024822', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024822');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Denso_GZ', '1000911455', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911455');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Denso_WX', '1000160851', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000160851');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Denza_New_Energy_SZ', '1000031532', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000031532');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DF_Motor_WH', '1000152009', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000152009');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DF_PV_WH', '1000023193', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000023193');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DF_Venucia_GZ', '1000029062', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029062');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFA_CC', '1000911443', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911443');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DF Lear_LZ', '1000172808', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000172808');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DF Lear_CQ', '1000166710', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166710');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFL_GZ', '1000014552', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014552');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFL_ZZ', '1000029062', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029062');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFLZM_LZ', '1000010767', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010767');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFSK_CQ', '1000013348', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000013348');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DFYL_HZ', '1000013449', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000013449');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Dingli_LH', '1000911459', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911459');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Doowon_YC', '1000911471', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911471');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Doutian_YC', '1000039441', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000039441');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DPCA_CD', '1000034508', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000034508');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DPCA_WH', '1000014573', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014573');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DRAC_WH', '1000020563', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020563');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'DYK_YC', '1000911479', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911479');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Eckerle_ZH', '1000025397', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025397');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ESTRA_SY', '1000018107', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018107');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAA_CC', '1000911506', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911506');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAA_CD', '1000042287', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000042287');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAA_FS', '1000015611', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015611');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAA_QD', '1000033124', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033124');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAA_TJ', '1000033125', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033125');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAW_CC', '1000181833', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000181833');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Faw_Valeo_CC', '1000911470', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911470');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Faw_Valeo_CD', '1000911450', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911450');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fawer_Denso_CC', '1000911478', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911478');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fawer_Denso_FS', '1000015612', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015612');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fawer_Denso_TJ', '1000911517', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911517');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAW-VW_CC', '1000004869', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000004869');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAW-VW_CD', '1000904837', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000904837');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FAW-VW_FS', '1000911514', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911514');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FCA_APAC_SH', '1000025496', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025496');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'FCA_SH', '1000037671', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000037671');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Feiying_CZ', '1000184148', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000184148');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fisher_CQ', '1000033744', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033744');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fisher_SH', '1000015610', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015610');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_BR', '60837', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '60837');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_NJ', '1000027127', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000027127');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_SA', '1000032453', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032453');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_CC', '1000911507', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911507');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_CD', '1000028698', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028698');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_CS', '1000040077', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040077');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_JX', '1000170237', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000170237');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_SH', '1000033870', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033870');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_SZ', '1000040073', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040073');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_TJ', '1000037060', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000037060');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Forvia_XA', '1000040079', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040079');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Futuris_WH', '1000173529', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000173529');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Futuris_QD', '1000173739', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000173739');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fuyao_SH', '1000027757', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000027757');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_FCA_CS', '1000010878', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010878');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_FCA_GZ', '1000025466', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025466');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_GZ', '1000007585', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007585');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_New_Energy_GZ', '1000042046', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000042046');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_YC', '1000042079', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000042079');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_CD', '1000911543', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911543');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_GY', '1000037766', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000037766');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_JN', '1000010793', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010793');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_JZ', '1000026672', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026672');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_LH', '1000005019', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000005019');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_NB', '1000010726', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010726');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_XA', '1000157572', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000157572');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_YW', '1000150777', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150777');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_YY', '1000039725', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000039725');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_ZJK', '1000032059', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032059');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GHAC_GZ', '1000035525', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035525');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GHAC_ZC', '1000028567', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028567');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GM_USA', '1000001286', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000001286');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Guoneng_TJ', '1000032210', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032210');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_BD', '1000010924', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010924');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_CQ', '1000043837', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000043837');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_DY', '1000175170', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000175170');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_JM', '1000162838', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000162838');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_PH', '1000156926', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000156926');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_RZ', '1000159462', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000159462');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_TJ', '1000162647', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000162647');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_TZ', '1000155614', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000155614');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_JX', '1000156926', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000156926');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_XS', '1000017879', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000017879');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GWM_ZJG', '1000166857', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166857');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Haikun_NC', '1000033207', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033207');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hanon_BJ', '1000911469', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911469');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hanon_CQ', '1000911458', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911458');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hanon_NC', '1000017878', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000017878');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hanon_YC', '1000018529', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018529');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hanteng_SR', '1000034706', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000034706');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HAPM_Magna_TJ', '1000035952', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035952');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HAPM_Magna_WH', '1000040995', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040995');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HAPM_Magna_XY', '1000033986', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033986');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HAPM_XF', '1000911481', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911481');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hengxin_WH', '1000015893', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015893');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hilex_CC', '1000911485', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911485');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hilex_CQ', '1000911504', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911504');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hilex_HZ', '1000025243', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025243');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hilex_TJ', '1000171390', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000171390');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HMTC', '1000038885', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000038885');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Honda_Motor_GZ', '1000021882', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021882');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Huachuang_HZ', '1000019989', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019989');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Huayue', '1000181652', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000181652');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'HXC_CQ', '1000911457', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911457');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Hyatt_ZJK', '1000032059', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032059');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Inteva_ZJ', '1000156601', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000156601');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Inteva_SN', '1000175817', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000175817');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Instic', '1000182170', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000182170');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'JAC_HF', '1000905813', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000905813');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'JAC_LCV_HF', '1000040913', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040913');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'JAC_MC', '1000020358', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020358');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'JAC_YZ', '1000020363', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020363');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Jifeng_CZ', '1000177093', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000177093');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Jifeng_SH', '1000182988', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000182988');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Jinggong_BD', '1000041245', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000041245');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'JMC_NC', '1000024018', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024018');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'KBWS_JY', '1000035014', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035014');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'KBWS_Kr', '1000023777', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000023777');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Keiper_CSU', '1000032870', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032870');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Keiper_SH', '1000019243', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019243');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Kwangjin_BJ', '1000911508', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911508');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Kwangjin_CQ', '1000030942', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000030942');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Kwangjin_DF', '1000018482', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018482');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Kwangjin_KS', '1000911484', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911484');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Kwangjin_SY', '1000911491', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911491');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lear_CQ', '1000157856', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000157856');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lear_SH', '1000046033', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000046033');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lianhong_FZ', '1000019072', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019072');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lifan_CQ', '1000007659', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007659');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'LKTJ_YT', '1000033261', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033261');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lynk_YY', '1000039725', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000039725');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Magna_CQ', '1000171761', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000171761');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Magna_KF', '1000016182', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000016182');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Magna_SZ', '1000911449', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911449');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Magna_BJ', '1000150914', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150914');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mahle_CD', '1000032861', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000032861');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mahle_NJ', '1000911520', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911520');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mahle_SH', '1000001967', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000001967');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mahle_SY', '1000019991', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019991');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mando_SZ', '1000172501', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000172501');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Marelli_XY', '1000030896', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000030896');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'MG_NJ', '1000007680', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007680');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mind_BD', '1000042073', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000042073');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mind_CQ', '1000046575', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000046575');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mind_TJ', '1000154590', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000154590');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mind_TZ', '1000166859', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166859');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mind_XS', '1000041938', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000041938');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mingfang_WX', '1000036762', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000036762');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Mobitech_SH', '1000027792', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000027792');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Motiontec_LZ', '1000020690', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020690');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Motiontec_WH', '1000911497', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911497');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'NCIC_BJ', '1000016889', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000016889');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'New_Energy_BJ', '1000044680', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000044680');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'NIO_SH', '1000029388', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029388');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'NITCO_GZ', '1000015113', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015113');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Nobo_BD', '1000044659', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000044659');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Nobo_HS', '1000175338', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000175338');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Nobo_ZJG', '1000169977', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000169977');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'NSL_SH', '1000028094', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028094');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Pangeo_CS', '1000911486', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911486');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'PATAC_SH', '1000005635', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000005635');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'PciP', '1000014870', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014870');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'PSA_SK', '1000900068', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000900068');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Pyeong_BJ', '1000911475', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911475');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Qoros_CSU', '1000911532', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911532');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBAC', '1000010486', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010486');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBAG_CC', '1000010126', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010126');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBAG_CD', '1000021025', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021025');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBAU', '1000009753', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000009753');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBBE', '1000010104', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010104');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBCD', '1000019650', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019650');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBCS', '1000021010', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021010');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBDI', '1000155942', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000155942');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBEC', '1000010226', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010226');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBEI ', '1000024188', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024188');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBFR', '1000031130', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000031130');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBHM', '1000006656', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000006656');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBIC', '1000010285', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010285');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBIN', '1000021660', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021660');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBJP', '1000006922', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000006922');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBKB ', '1000029480', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029480');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBLA ', '1000002238', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000002238');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBLC ', '1000025162', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025162');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBMC', '1000017586', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000017586');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBME', '1000000806', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000000806');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBSA', '1000006844', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000006844');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBSI', '1000009470', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000009470');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBSM', '1000014870', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014870');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBSR', '1000019888', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019888');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBTY', '1000018345', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018345');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBUS', '1000012879', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012879');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBVN', '1000044230', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000044230');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Rentai_YK', '1000026597', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026597');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Rongbang_WZ', '1000165684', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000165684');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ruiqing_JZ', '1000038437', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000038437');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_GM_SH', '1000904136', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000904136');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_GM_SY', '1000010759', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010759');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_GM_WH', '1000019489', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019489');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_GM_YT', '1000010724', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010724');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_ND', '1000045129', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000045129');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_NJ', '1000035686', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035686');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_SH', '1000007661', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007661');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_VW_CS', '1000021356', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021356');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_VW_NB', '1000017579', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000017579');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_VW_NJ', '1000010819', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010819');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_VW_SH', '1000004873', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000004873');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_VW_YZ', '1000911441', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911441');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_WX', '1000025715', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025715');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAIC_ZZ', '1000035464', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035464');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SAMAP_SH', '1000911495', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911495');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sanden_CD', '1000044376', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000044376');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sanden_CQ', '1000026601', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026601');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sanden_LZ', '1000163523', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000163523');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sanden_TJ', '1000025883', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000025883');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sanli_MY', '1000040846', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040846');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SCI_NB', '1000044661', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000044661');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SDAAC_CSU', '1000001736', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000001736');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SDAAC_SY', '1000018107', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000018107');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SDAAC_YT', '1000911512', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911512');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SEG_CS', '1000035068', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035068');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SGMW_LZ', '1000007602', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007602');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SHD_BJ', '1000911463', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911463');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Shengtai_TA', '1000030336', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000030336');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Shibao_JL', '1000158797', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000158797');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ShzP_SZ', '1000006741', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000006741');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Seres_CQ', '1000034850', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000034850');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Sinotruk_JN', '1000012202', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012202');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'SongZ_HF', '1000150493', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150493');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Songz_SH', '1000016967', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000016967');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Spotlight_SZ', '1000166288', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166288');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'STEC_BD', '1000029412', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029412');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'STEC_NJ', '1000028877', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028877');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'STEC_SH', '1000014577', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000014577');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tachi-S_JS', '1000911473', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911473');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tesla_SH', '1000150576', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150576');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TFDA_CC', '1000911479', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911479');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TFDA_FS', '1000015612', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015612');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TgP', '1000179010', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000179010');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TI_SH', '1000042203', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000042203');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tianqiu_LB', '1000029063', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029063');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tianqiu_WZ', '1000911490', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911490');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TKP_CC', '1000038023', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000038023');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TKP_SH', '1000045673', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000045673');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tri-Ring_SY', '1000040159', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000040159');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Tuopu_NB', '1000162268', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000162268');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'UAES_XA', '1000007545', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000007545');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'UAES_SH', '1000000925', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000000925');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_CC', '1000030335', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000030335');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_CD', '1000045583', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000045583');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_FS', '1000027902', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000027902');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_GZ', '1000911460', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911460');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_JP', '1000012445', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012445');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_JZ', '1000150257', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150257');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_Kr', '1000152287', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000152287');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_NJ', '1000911477', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911477');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_Indonesia', '1000154690', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000154690');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_SS', '1000904539', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000904539');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Valeo_TJ', '1000019178', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019178');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Volvo_SH', '1000015185', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000015185');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Volvo_TZ', '1000039903', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000039903');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Volvo_DQ', '1000035691', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000035691');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Voyah_WH', '1000157204', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000157204');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'VW_HF', '1000165624', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000165624');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Wancheng_ZJG', '1000022971', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000022971');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Wanjiang_SH', '1000911492', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911492');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'WDHAC_WH', '1000010730', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010730');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'WHDH_BD', '1000020707', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000020707');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'WHDH_CQ', '1000036492', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000036492');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'WHDH_WH', '1000911489', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911489');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'WM_WZ', '1000029414', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000029414');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiaomi_BJ', '1000168962', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000168962');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiaopeng_GZ', '1000033788', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000033788');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiaopeng_WH', '1000170167', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000170167');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiaopeng_ZQ', '1000153898', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000153898');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiezhong_NJ', '1000021696', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000021696');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Xiezhong_WH', '1000155420', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000155420');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Yahoo_CC', '1000046527', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000046527');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_CS', '1000024922', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000024922');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_CSU', '1000150226', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150226');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Fuyao_WD', '1000188663', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000188663');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_LF', '1000019992', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000019992');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_NB', '1000150259', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000150259');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_SH_JD', '1000911453', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911453');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_SH_PD', '1000010527', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000010527');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_YZ', '1000037786', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000037786');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_SY', '1000017626', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000017626');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_WH', '1000028418', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000028418');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_WHU', '1000911454', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911454');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YF_YT', '1000016154', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000016154');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Yiwei_HZ', '1000034030', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000034030');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Yinlun_SH', '1000174362', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000174362');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Yuxin_WH', '1000026183', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000026183');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Yuxin_XX', '1000022684', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000022684');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Faurecia_CD', '1000155234', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000155234');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YWM_WH', '1000911472', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911472');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'YZM_ZS', '1000911488', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000911488');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'OTOTRIM', '0000014682', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '0000014682');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Rollax_NJ', '1000164522', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000164522');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Zhuo Jun_CZ', '1000166082', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000166082');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Zhongjia_CD', '1000012941', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000012941');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ADIENT_TH', '1000174010', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000174010');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ZNA_ZZ', '1000005003', 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = '1000005003');

-- Customers without Cust_ID (CODE will be NULL)
INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Brose_IN', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Brose_IN' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BMW_DE', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'BMW_DE' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'CaP', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'CaP' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Dacia', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Dacia' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_NA', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Ford_NA' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_Thailand', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Ford_Thailand' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Ford_MX', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Ford_MX' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'GAC_HZ', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'GAC_HZ' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_CX', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Geely_CX' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_QT', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Geely_QT' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Geely_MS', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Geely_MS' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Honda_CA', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Honda_CA' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Jifeng_AH', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Jifeng_AH' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Luoke_QD', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Luoke_QD' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'PSA_FR', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'PSA_FR' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'RBTR', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'RBTR' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TIP', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'TIP' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'TOGG', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'TOGG' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Skywell_NJ', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Skywell_NJ' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Spotlight_ZJG', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Spotlight_ZJG' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'ADITYA', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'ADITYA' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Spolight_ZJG', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Spolight_ZJG' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'BMW_SY', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'BMW_SY' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Lear_SZ', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Lear_SZ' AND CODE IS NULL);

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), 'Zhongqi_JN', NULL, 'SYSTEM', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE NAME = 'Zhongqi_JN' AND CODE IS NULL);

COMMIT;
